### ISSUE TITLE
How to bring my bicycle

### ISSUE THREAD

**Issue by WaoSan** [cycle-journey/RouteBook#1]
问题来了，车怎么整过去,
do you have any detail plan???

**Comment by Alfonsxh** [comment]
good question

**Comment by Domado** [comment]
有道理

**Comment by dj9399** [comment]
巴士直接放箱，火车要打包（淘宝车包）

**Comment by Alfonsxh** [comment]
可以寄到旅馆，让老板保管。记得有个骑行俱乐部，能够做这些的

**Comment by Alfonsxh** [comment]
> 巴士直接放箱，火车要打包（淘宝车包）



> 有道理

可以寄到旅馆，让老板保管。记得有个骑行俱乐部，能够做这些的
